### ISSUE TITLE
Installing on the RockPro64

### ISSUE THREAD

**Issue by epsilon-0** [krjdev/rock64_openbsd#3]
I've been trying to install OpenBSD on the RockPro64 but I've been running into this error:
```
>> OpenBSD/arm64 BOOTAA64 0.16
open(tftp0a:/etc/boot.conf): Operation not permitted
boot> 
booting tftp0a:/bsd: open tftp0a:/bsd: Operation not permitted
 failed(1). will try /bsd
boot> 
booting tftp0a:/bsd: open tftp0a:/bsd: Operation not permitted
 failed(1). will try /bsd
Turning timeout off.
boot> 
```
Is there any way to know what is happening and how to fix it?

**Comment by krjdev** [comment]
The Link to Ayufan's U-Boot SPI Flasher Image in this tutorial is only for the ROCK64 (without Pro).
Could you retry the first step in this tutorial with the right image **u-boot-flash-spi-rockpro64.img.xz** for the ROCK64Pro?

You can find the latest releases at the following link:
[Ayufan's U-Boot Releases](https://github.com/ayufan-rock64/linux-u-boot/releases/)

If it also not work, then please try an older release of the U-Boot SPI Flasher image.
I don't have such a type of board at this time, so I can't test it.

**Comment by epsilon-0** [comment]
Yes, I've tried with the `u-boot-flash-spi-rockpro64.img.xz` but I received this error.
I'll try to use an older version and see if it changes anything.

**Comment by epsilon-0** [comment]
I have a question, if I get the following on booting with the img file:
```
mmc1 is current device
Scanning mmc 1:2...
Found U-Boot script /boot.scr
reading /boot.scr
827 bytes read in 2 ms (403.3 KiB/s)
## Executing script at 00500000
SF: Detected gd25q128 with page size 256 Bytes, erase size 4 KiB, total 16 MiB
reading rkspi_loader.img
1461780 bytes read in 156 ms (8.9 MiB/s)
SF: 4194304 bytes @ 0x0 Erased: OK
device 0 offset 0x0, size 0x164e14
SF: 1461780 bytes @ 0x0 Written: OK
```
where it is 0x0 instead of the 0x8000 as in your output, is this a problem?

**Comment by krjdev** [comment]
No. You should read :

> Written: OK

(Seems the SPI EEPROM of the ROCK64Pro has another address offset.)

**Comment by epsilon-0** [comment]
I used the newest snapshot and am running the -current version of OpenBSD and that solved the issue.

**Comment by krjdev** [comment]
Okay, thanks for the information.
