### ISSUE TITLE
Keyboard input not recognized when attempting to install

### ISSUE THREAD

**Issue by nura24** [krjdev/rock64_openbsd#4]
With 'Option 2' method, it gets as far as 
.
.
softraid0 at root
scsibus1 at softraid0: 256 targets
bootfile: sd0a:/bsd
boot device: sd0
root on rd0a swap on rd0b dump on rd0b
WARNING: bad clock chip time
WARNING: CHECK AND RESET THE DATE!
erase ^?, werase ^W, kill ^U, intr ^C, status ^T

Welcome to the OpenBSD/arm64 6.7 installation program.
(I)nstall, (U)pgrade, (A)utoinstall or (S)hell? 
.
.
Above output is with 1500000 baud.  

At 115200, random characters are displayed and after that has paused and 'I" is pressed, it does not recognize the input.  It echoes back graphic char.   Also, any particular reason for using 1500000?   PuTTY does not support that rate.

Thanks!

**Comment by krjdev** [comment]
Thanks you for the feedback.

The second option was the old variant to install OpenBSD on the board. Seems the baud rate should also be 1500000
when the OpenBSD installer starts. Sorry, my mistake. Not verified the second option with OpenBSD 6.7.

> Also, any particular reason for using 1500000?

It depends on the used Firmware (U-Boot) on the board and the Device-Tree blob. It's compiled with the default rate of 1500000. This baud rate is also used in the Device-Tree sources. AFAIK, there was a discussion in the PINE64 forum why this specific baud rate is used. Supposedly only this baud rate is supported by the SoC.

But also works with 115200. Just simple change the board configuration file and the Device-Tree source from U-Boot and recompile it.

**Comment by nura24** [comment]
Thank you for your quick response.

For now I have installed OpenBSD on Raspberry Pi 3B+. When I have some more time I will try Option 1.
