### ISSUE TITLE
USB ports

### ISSUE THREAD

**Issue by zelleb** [krjdev/rock64_openbsd#5]
Hey, just installed the latest snapshot and none of the USB ports seem to work. I tried different sticks and external HDDs, but none of them even power up.

Edit: I tried a few other things (your provided images, selfbuild images, current snapshots and stable 6.7 images). but USB just won't work.

here is my dmesg:

`OpenBSD 6.7 (GENERIC.MP) #602: Thu May  7 13:45:48 MDT 2020
    deraadt@arm64.openbsd.org:/usr/src/sys/arch/arm64/compile/GENERIC.MP
real mem  = 4211367936 (4016MB)
avail mem = 4007436288 (3821MB)
mainbus0 at root: Pine64 Rock64
cpu0 at mainbus0 mpidr 0: ARM Cortex-A53 r0p4
cpu0: 32KB 64b/line 2-way L1 VIPT I-cache, 32KB 64b/line 4-way L1 D-cache
cpu0: 256KB 64b/line 16-way L2 cache
efi0 at mainbus0: UEFI 2.8
efi0: Das U-Boot rev 0x20201000
apm0 at mainbus0
psci0 at mainbus0: PSCI 1.1, SMCCC 1.2
syscon0 at mainbus0: "syscon"
"io-domains" at syscon0 not configured
"grf-gpio" at syscon0 not configured
"power-controller" at syscon0 not configured
"reboot-mode" at syscon0 not configured
rkclock0 at mainbus0
syscon1 at mainbus0: "syscon"
"usb2-phy" at syscon1 not configured
ampintc0 at mainbus0 nirq 160, ncpu 4 ipi: 0, 1: "interrupt-controller"
rkpinctrl0 at mainbus0: "pinctrl"
rkgpio0 at rkpinctrl0
rkgpio1 at rkpinctrl0
rkgpio2 at rkpinctrl0
rkgpio3 at rkpinctrl0
"fit-images" at mainbus0 not configured
"opp_table0" at mainbus0 not configured
simplebus0 at mainbus0: "bus"
"dmac" at simplebus0 not configured
"arm-pmu" at mainbus0 not configured
rkdrm0 at mainbus0
drm0 at rkdrm0
agtimer0 at mainbus0: tick rate 24000 KHz
"xin24m" at mainbus0 not configured
"i2s" at mainbus0 not configured
"spdif" at mainbus0 not configured
com0 at mainbus0: ns16550, no working fifo
com0: console
rkiic0 at mainbus0
iic0 at rkiic0
rkpmic0 at iic0 addr 0x18: RK805
"spi" at mainbus0 not configured
"watchdog" at mainbus0 not configured
rktemp0 at mainbus0
"efuse" at mainbus0 not configured
"gpu" at mainbus0 not configured
"video-codec" at mainbus0 not configured
"iommu" at mainbus0 not configured
"vop" at mainbus0 not configured
"iommu" at mainbus0 not configured
"hdmi" at mainbus0 not configured
"codec" at mainbus0 not configured
"phy" at mainbus0 not configured
dwmmc0 at mainbus0: 50 MHz base clock
sdmmc0 at dwmmc0: 4-bit, sd high-speed, mmc high-speed, dma
dwmmc1 at mainbus0: 50 MHz base clock
sdmmc1 at dwmmc1: 8-bit, mmc high-speed, dma
dwge0 at mainbus0: address 46:28:46:d8:6d:13
rgephy0 at dwge0 phy 0: RTL8169S/8110S/8211 PHY, rev. 6
ehci0 at mainbus0
usb0 at ehci0: USB revision 2.0
uhub0 at usb0 configuration 1 interface 0 "Generic EHCI root hub" rev 2.00/1.00 addr 1
ohci0 at mainbus0: version 1.0
"usb" at mainbus0 not configured
"external-gmac-clock" at mainbus0 not configured
"sdmmc-regulator" at mainbus0 not configured
"vcc-host-5v-regulator" at mainbus0 not configured
"vcc-host1-5v-regulator" at mainbus0 not configured
"vcc-sys" at mainbus0 not configured
"ir-receiver" at mainbus0 not configured
"leds" at mainbus0 not configured
"sound" at mainbus0 not configured
"spdif-dit" at mainbus0 not configured
"dmc" at mainbus0 not configured
"usb" at mainbus0 not configured
cpu1 at mainbus0 mpidr 1: ARM Cortex-A53 r0p4
cpu1: 32KB 64b/line 2-way L1 VIPT I-cache, 32KB 64b/line 4-way L1 D-cache
cpu1: 256KB 64b/line 16-way L2 cache
cpu2 at mainbus0 mpidr 2: ARM Cortex-A53 r0p4
cpu2: 32KB 64b/line 2-way L1 VIPT I-cache, 32KB 64b/line 4-way L1 D-cache
cpu2: 256KB 64b/line 16-way L2 cache
cpu3 at mainbus0 mpidr 3: ARM Cortex-A53 r0p4
cpu3: 32KB 64b/line 2-way L1 VIPT I-cache, 32KB 64b/line 4-way L1 D-cache
cpu3: 256KB 64b/line 16-way L2 cache
usb1 at ohci0: USB revision 1.0
uhub1 at usb1 configuration 1 interface 0 "Generic OHCI root hub" rev 1.00/1.00 addr 1
scsibus0 at sdmmc0: 2 targets, initiator 0
sd0 at scsibus0 targ 1 lun 0: <SD/MMC, SE32G, 0080> removable
sd0: 30436MB, 512 bytes/sector, 62333952 sectors
sdmmc1: can't enable card
vscsi0 at root
scsibus1 at vscsi0: 256 targets
softraid0 at root
scsibus2 at softraid0: 256 targets
bootfile: sd0a:/bsd
boot device: sd0
root on sd0a (8798a6d768c05931.a) swap on sd0b dump on sd0b
rkdrm0: no display interface ports configured
arp info overwritten for 192.168.1.30 by 00:24:d7:b3:e5:28 on dwge0
com0: 1 silo overflow, 0 ibuf overflows
arp info overwritten for 192.168.1.30 by 00:24:d7:b3:e5:28 on dwge0
`

**Comment by krjdev** [comment]
Sorry for my late response.

Currently tried it with different Device-Tree files (also the default from OpenBSD port tree). 
But always run into the same issue.

I think the problem with these Device-Tree files is the **usb2-phy** node. Which isn't configured correctly from OpenBSD.
Also tried a older version of the device tree from vanilla U-Boot v2019.07. Since this version there is an official board support.
But the same issue.

I will keep you up to date, when I find a solution for this issue.

**Comment by zelleb** [comment]
Thank you. Can't wait to run OpenBSD on this thing :grinning:

**Comment by ksio2125** [comment]
quick update to openBSD  6.8 issue still persist.

**Comment by Fede068** [comment]
Hello, I've the same issue. After install OpenBSD 6.7 successfully on my Rock64 and then also Upgrade to v6.8 still no support for usb connected dev. Are there news or perspectives on a solution?

**Comment by jyelloz** [comment]
If you use a powered USB hub, you should be able to use the plain, non-OTG USB 2.0 port (bottom center) with the default OpenBSD 6.8 install, probably 6.7 but I have not tested that. My experience is that it's fully functional minus the electricity supply. I am able to use a SSD to store my local development environment for learning how to write some of the missing RK3328 drivers. You can almost use the USB 3.0 port in the same way if you add a device tree node for the USB3 port based on https://github.com/rockchip-linux/kernel/blob/develop-4.19/arch/arm64/boot/dts/rockchip/rk3328.dtsi#L1376-L1392 you can get a similarly un-powered USB3 port that is about 90% broken. It will recognize powered things that you plug in with no problem and I was able to mount that same SSD using a powered usb3 hub and a SATA adapter that way but it will hang after transferring a little bit of data. I have been looking into what is the correct way to initialize the 3328's USB2/3/OTG PHYs since that seems to be what's missing in OpenBSD but the Technical Reference Manual is pretty uninformative about USB initialization and the rockchip linux fork is basically a substitute for a TRM that's kind of difficult to navigate.

**Comment by jyelloz** [comment]
Update: I was looking around at the forum and saw https://forum.pine64.org/showthread.php?tid=5001 which was pinned at the top. The basics are that the USB power lines are all tied together and controlled by GPIOA, port 2 in the rock64. I don't think the GPIOs are properly exported to userspace in OpenBSD yet for the gpioctl tool but you can just write data to raw memory if you want to get your USB ports powered up, though it requires switching on access to kmem and operating in insecure mode. You will need the following sysctls set:
```
kern.allowkmem=1
kern.securelevel=-1
```

Then you can write some really simple python code to modify the memory-mapped register directly from userspace (must run as root in insecure mode):
```py
GPIO0 = 0xFF210000
# On/Off
GPIO_SWPORTA_DR = 0x0
# Direction
GPIO_SWPORTA_DDR = 0x4

with open('/dev/mem', 'r+b') as mem:
    mem.seek(GPIO0 + GPIO_SWPORTA_DDR)
    current_directions, = struct.unpack('I', mem.read(4))
    new_directions = current_directions | 0b100
    mem.seek(GPIO0 + GPIO_SWPORTA_DDR)
    mem.write(struct.pack('>I', new_directions))
    mem.flush()

    mem.seek(GPIO0 + GPIO_SWPORTA_DR)
    current_data, = struct.unpack('I', mem.read(4))
    new_data = current_data & 0xfffffffb
    mem.seek(GPIO0 + GPIO_SWPORTA_DR)
    mem.write(struct.pack('>I', new_data))
    mem.flush()
```

You might also be able to accomplish the same thing by adding a little bit to your u-boot startup script and use its `mw` command within to switch some stuff at the same memory locations before entering OpenBSD and then you won't need to mess up your security settings.

**Comment by krjdev** [comment]
Sorry for my very late response.

@zelleb Thanks, for this clarification. Last time I hadn't enough time to investigate this issue. I think as long as the OpenBSD developers don't fix this issue in the USB driver from the RK3328, we use your suggestion with the U-Boot `mw` command. I think I will write a U-Boot script and add it in this tutorial. Also must update this tutorial to OpenBSD 6.8.

**Comment by krjdev** [comment]
@jyelloz 
I tried your Python script...

First: 
`import struct` is missing in the script.

Second:
I doesn't work on my test system (version 2.0). So my question is, why you clear the `bit 2` in  `GPIO_SWPORTA_DR` register? Low-active? Haven't read the pinned thread in the PINE64 forum yet.

**Comment by krjdev** [comment]
@jyelloz 
It's working with the `mw` command. Tried it...
```
=> mw 0xFF210000 0x00000000 1
```
In your Python script is `import struct` missing. Correct?

**Comment by krjdev** [comment]
@jyelloz 
I have updated the tutorial.

Can I mention in you in the credits section in my tutorial for investigating and solving this issue?

Thank you very much!

**Comment by Fede068** [comment]
Hello Johannes, thank you very much for this important improvement. At the moment I've already installed OpenBSD  6.8 and I don't want to re-install everything. Sorry for my noob question: Is it possible to get this one USB port working starting the tutorial from step 6?

**Comment by krjdev** [comment]
Hi @Fede068 

Just copy the [U-Boot script](https://github.com/krjdev/rock64_openbsd/blob/master/bin/rock64/U-Boot_v2021.01/boot.scr) (my prebuilt) on the FAT partition of the microSD card and reboot. Don't know which version of U-Boot you use. But I think the script binary should be compatible.

**Comment by Fede068** [comment]
Hello,
I'm using with U-Boot v2020.07, the previous one. I'll try it and let you know. Thanks.

**Comment by Fede068** [comment]
Hi @krjdev,

After copy and reboot I've connected an 16GB Intenso pen drive at the lower usb port as indicated and it works. Didn't tried with an external SSD yet but I think should be the same. Thank you and @jyelloz for this workaround.

**Comment by krjdev** [comment]
Hi @Fede068 ,

Perfect!
Thanks for the feedback.

**Comment by krjdev** [comment]
Partially fixed with release [openbsd68_v1.0](https://github.com/krjdev/rock64_openbsd/releases/tag/openbsd68_v1.0) from this tutorial.
