### ISSUE TITLE
Serial port TXD/RXD labels

### ISSUE THREAD

**Issue by ed-davies** [krjdev/rock64_openbsd#7]
I think the labels for TXD and RXD on the [first picture](https://github.com/krjdev/rock64_openbsd/blob/master/img/rock64-serial.png) are reversed. According to the [PINE64 documentation](https://files.pine64.org/doc/rock64/ROCK64_Pi-2%20_and_Pi_P5+_Bus.pdf) and various Raspberry Pi pages the connections should be:

6 - Ground
8 - TXD
10 - RXD

This could really confuse somebody using a different USB/serial adapter.

**Comment by krjdev** [comment]
Thanks for the hint.

It was my mistake (Wiring issue in my test arrangement). 

Should be correct with the latest [commit](https://github.com/krjdev/rock64_openbsd/commit/f0444efcbbdab9e14f71e9d891dfc404073b18a5) now.

Can you please verify the new image?
If it's okay now, I can create a new (bug-fix) release.

**Comment by ed-davies** [comment]
Yes, the image on the front page now matches my understanding of the other documentation available. Thanks for the quick fix.
